name: Build

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"
      - "!master"
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - uses: actions/checkout@v2
      #   with:
      #     repository: kernel-mod/browser
      #     path: browser

      # - uses: actions/cache@v2
      #   with:
      #     path: ~/.pnpm-store
      #     key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: true

      - name: Build ASAR
        run: |
          pnpm run build
